version: "3.9"

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: Dockerfile
    restart: always
    deploy:
      replicas: 1
      mode: replicated
    ports:
      - "8081:8081"
  url-shortener-service:
    build:
      context: ./../url-shortener-service
      dockerfile: ./Dockerfile
    restart: always
    deploy:
      replicas: 1
      mode: replicated
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "50001:50001"
  
  redirect-service:
    build:
      context: ./../redirect-service
      dockerfile: ./Dockerfile
    restart: always
    deploy:
      replicas: 1
      mode: replicated
    ports:
      - "50002:50002"
  
  analytics-service:
    build:
      context: ./../analytics-service
      dockerfile: ./Dockerfile
    restart: always
    deploy:
      replicas: 1
      mode: replicated
    env_file:
      - .env
    ports:
      - "50003:50003"
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urls
    ports:
      - "5432:5432"
    volumes:
      - "./db-data/postgres/:/var/lib/postgresql/data/"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5