// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: url.proto

package url

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LongURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longurl       string                 `protobuf:"bytes,1,opt,name=longurl,proto3" json:"longurl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongURL) Reset() {
	*x = LongURL{}
	mi := &file_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongURL) ProtoMessage() {}

func (x *LongURL) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongURL.ProtoReflect.Descriptor instead.
func (*LongURL) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0}
}

func (x *LongURL) GetLongurl() string {
	if x != nil {
		return x.Longurl
	}
	return ""
}

type ShortURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shorturl      string                 `protobuf:"bytes,1,opt,name=shorturl,proto3" json:"shorturl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURL) Reset() {
	*x = ShortURL{}
	mi := &file_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURL) ProtoMessage() {}

func (x *ShortURL) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURL.ProtoReflect.Descriptor instead.
func (*ShortURL) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{1}
}

func (x *ShortURL) GetShorturl() string {
	if x != nil {
		return x.Shorturl
	}
	return ""
}

var File_url_proto protoreflect.FileDescriptor

const file_url_proto_rawDesc = "" +
	"\n" +
	"\turl.proto\x12\x03url\"#\n" +
	"\aLongURL\x12\x18\n" +
	"\alongurl\x18\x01 \x01(\tR\alongurl\"&\n" +
	"\bShortURL\x12\x1a\n" +
	"\bshorturl\x18\x01 \x01(\tR\bshorturl2h\n" +
	"\n" +
	"URLService\x12/\n" +
	"\x10GenerateShortURL\x12\f.url.LongURL\x1a\r.url.ShortURL\x12)\n" +
	"\n" +
	"GetLongURL\x12\r.url.ShortURL\x1a\f.url.LongURLB\aZ\x05./urlb\x06proto3"

var (
	file_url_proto_rawDescOnce sync.Once
	file_url_proto_rawDescData []byte
)

func file_url_proto_rawDescGZIP() []byte {
	file_url_proto_rawDescOnce.Do(func() {
		file_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_proto_rawDesc), len(file_url_proto_rawDesc)))
	})
	return file_url_proto_rawDescData
}

var file_url_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_url_proto_goTypes = []any{
	(*LongURL)(nil),  // 0: url.LongURL
	(*ShortURL)(nil), // 1: url.ShortURL
}
var file_url_proto_depIdxs = []int32{
	0, // 0: url.URLService.GenerateShortURL:input_type -> url.LongURL
	1, // 1: url.URLService.GetLongURL:input_type -> url.ShortURL
	1, // 2: url.URLService.GenerateShortURL:output_type -> url.ShortURL
	0, // 3: url.URLService.GetLongURL:output_type -> url.LongURL
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_url_proto_init() }
func file_url_proto_init() {
	if File_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_proto_rawDesc), len(file_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_proto_goTypes,
		DependencyIndexes: file_url_proto_depIdxs,
		MessageInfos:      file_url_proto_msgTypes,
	}.Build()
	File_url_proto = out.File
	file_url_proto_goTypes = nil
	file_url_proto_depIdxs = nil
}
