// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shorturl      string                 `protobuf:"bytes,1,opt,name=shorturl,proto3" json:"shorturl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURL) Reset() {
	*x = ShortURL{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURL) ProtoMessage() {}

func (x *ShortURL) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURL.ProtoReflect.Descriptor instead.
func (*ShortURL) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *ShortURL) GetShorturl() string {
	if x != nil {
		return x.Shorturl
	}
	return ""
}

type AnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shorturl      string                 `protobuf:"bytes,1,opt,name=shorturl,proto3" json:"shorturl,omitempty"`
	TotalClicks   int32                  `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsResponse) Reset() {
	*x = AnalyticsResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsResponse) ProtoMessage() {}

func (x *AnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsResponse.ProtoReflect.Descriptor instead.
func (*AnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyticsResponse) GetShorturl() string {
	if x != nil {
		return x.Shorturl
	}
	return ""
}

func (x *AnalyticsResponse) GetTotalClicks() int32 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\x1a\x1bgoogle/protobuf/empty.proto\"&\n" +
	"\bShortURL\x12\x1a\n" +
	"\bshorturl\x18\x01 \x01(\tR\bshorturl\"R\n" +
	"\x11AnalyticsResponse\x12\x1a\n" +
	"\bshorturl\x18\x01 \x01(\tR\bshorturl\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x05R\vtotalClicks2\x92\x01\n" +
	"\x10AnalyticsService\x12A\n" +
	"\fGetAnalytics\x12\x13.analytics.ShortURL\x1a\x1c.analytics.AnalyticsResponse\x12;\n" +
	"\fAddAnalytics\x12\x13.analytics.ShortURL\x1a\x16.google.protobuf.EmptyB\rZ\v./analyticsb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_analytics_proto_goTypes = []any{
	(*ShortURL)(nil),          // 0: analytics.ShortURL
	(*AnalyticsResponse)(nil), // 1: analytics.AnalyticsResponse
	(*emptypb.Empty)(nil),     // 2: google.protobuf.Empty
}
var file_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.GetAnalytics:input_type -> analytics.ShortURL
	0, // 1: analytics.AnalyticsService.AddAnalytics:input_type -> analytics.ShortURL
	1, // 2: analytics.AnalyticsService.GetAnalytics:output_type -> analytics.AnalyticsResponse
	2, // 3: analytics.AnalyticsService.AddAnalytics:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
